outdir: ./test/
injection_file: /home/deep.chatterjee/git.ligo.org/mdc-analytics/injections-minSNR-4.hdf5 
ifos: ["H1", "L1", "V1"]
channels: ["H1:GDS-CALIB_STRAIN_CLEAN_INJ1_O4Replay", "L1:GDS-CALIB_STRAIN_CLEAN_INJ1_O4Replay", "V1:Hrec_hoft_16384Hz_INJ1_O4Replay"]
sample_rate: 2048
strain_data_dir: 
